name: Smoke
on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo "package=${{ inputs.package_name }}"
